name: ASP.NET Core with Angular Workflow
on:
  workflow_call:
env:
  AZURE_WEBAPP_NAME: SSW-Devops-template-app
  AZURE_WEBAPP_PACKAGE_PATH: .\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: .
jobs:

  deploy:
    runs-on: windows-latest
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.SSW_Devops_template_app_6E5B }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

